### ISSUE TITLE
Auto Replant server CLI command?

### ISSUE THREAD

**Issue by Harcagnel** [nivoridocs/strawgolem#7]
Is there a CLI command to turn on Auto Replant? If not how do you turn on this feature via commands? We are running a server to which I am an admin but my character does not have admin rights. So I was going to turn it on through my server account if I could. Thank you for any information here.

**Comment by un-nubivago** [comment]
No, there aren't any CLI command in Straw Golem and I'm not going to implement them. If you have admin privileges, you may be able to edit the `strawgolem.cfg` file in your server's `config` folder, changing the line `B:replantEnabled=false` to `B:replantEnabled=true`, then restart the server.
